# source 'https://github.com/CocoaPods/Specs.git'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'XC_RN_UI' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNSyanImagePicker', :path => '../node_modules/react-native-syan-image-picker'

  target 'XC_RN_UITests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'XC_RN_UI-tvOS' do
  # Pods for XC_RN_UI-tvOS

  target 'XC_RN_UI-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
